---
- yum:
    name: monit
    state: latest

- template:
    src: monit.conf.j2
    dest: /etc/monit.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - reload monit

- service:
    name: monit
    state: started
    enabled: yes
